#ifndef OOP_LAB_01_DEFINES_H
#define OOP_LAB_01_DEFINES_H

#define OK 0
#define NOFILE 1
#define NOTENOUGHPOINTS 2
#define ERRORWHILEREADINGPOINTS 3
#define ERRORWHILEREADINGEDGES 4
#define NOTENOUGHEDGES 5
#define NOFREESPACE 6

#endif //OOP_LAB_01_DEFINES_H
